### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: ER_CON_COUNT_ERROR: Too many connections

### ISSUE THREAD

**Issue by XieTongXue** [JiangquanWu/myExpressModel#1]
多次刷新页面请求查询、保存等操作；会出现以下错误：

`(node:4828) UnhandledPromiseRejectionWarning: Error: ER_CON_COUNT_ERROR: Too many connections
    at Handshake.Sequence._packetToError (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Protocol._enqueue (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\mysql\lib\Pool.js:48:16)
    at E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\my-express-model\database\mysql\mysqlConnection.js:39:10
    at new Promise (<anonymous>)
    at Object.connect (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\my-express-model\database\mysql\mysqlConnection.js:30:10)
    at Mysql.connect (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\my-express-model\database\mysql\index.js:29:26)
    at Function.connect (E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\my-express-model\index.js:402:25)
    at E:\Mine\project\node\异常监控服务\error_watch\error_watch_server\node_modules\my-express-model\index.js:370:31
<node_internals>/internal/process/warning.js:43`

看起来是操作后连接没有释放导致存在多个数据库连接？源码中挺多个方法没有关闭连接，只有save方法有connection.end()；但操作是异步的，这边这样会存在一定的概率关闭不了连接，比如这段代码：
`  
this.constructor.insertRecord(record, connection, this.constructor.resolveCallback(resolve, callback));
`
`this.pool && connection.end();`

**Comment by WuJiangquan** [comment]
connection.end()//或者connection.detroy();

**Comment by XieTongXue** [comment]
1.1.5版本已修复
